repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2048']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.4
    hooks:
      - id: sqlfluff-lint
        files: ^models/.*\.sql$
        additional_dependencies:
          - dbt-core==1.8.0
          - dbt-duckdb==1.8.1
          - sqlfluff-templater-dbt
